name: update_deps

on:
  workflow_dispatch: #allow manual triggering
  schedule:
      - cron: "0 4 * * *"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: setup git
        run: | 
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: update
        run: |
          MESSAGE=""

          nix flake update --no-warn-dirty --commit-lock-file

          nix run .#fetcher

          nix run nixpkgs#nix-update -- -F legacyPackages.$(nix eval --raw --impure --expr 'builtins.currentSystem').spicetify
          
          git add -A

          git commit --amend -m "CI update $(date -I)" -m "$MESSAGE"

          git push origin HEAD:${{ github.ref_name }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

